#pragma checksum "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor" "{8829d00f-11b8-4213-878b-770e8597ac16}" "8d242fad32995d7817ec8835a5aa64e98e170746d4375e4fe2759bcd3d363bbd"
// <auto-generated/>
#pragma warning disable 1591
namespace 
#nullable restore
#line (1,12)-(1,26) "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor"
Suran.ShareArk

#line default
#line hidden
#nullable disable
{
    #line default
    using global::System;
    using global::System.Collections.Generic;
    using global::System.Linq;
    using global::System.Threading.Tasks;
    using global::Microsoft.AspNetCore.Components;
#nullable restore
#line (3,2)-(3,17) "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor"
using AntDesign

#nullable disable
    ;
    #line default
    #line hidden
    #nullable restore
    public partial class ShareArkUI : 
#nullable restore
#line (2,11)-(2,71) "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor"
Alife.Framework.ModuleUIBase<ShareArkModule, ShareArkConfig>

#line default
#line hidden
#nullable disable

    #nullable disable
    {
        #pragma warning disable 1998
        protected override void BuildRenderTree(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
        {
            __builder.OpenElement(0, "div");
            __builder.AddAttribute(1, "style", "background: #fff; padding: 20px; border-radius: 8px; overflow: hidden;");
            __builder.OpenComponent<global::AntDesign.Flex>(2);
            __builder.AddComponentParameter(3, nameof(global::AntDesign.Flex.
#nullable restore
#line (8,11)-(8,18) "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor"
Justify

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::OneOf.OneOf<global::AntDesign.FlexJustify, global::System.String>>(
#nullable restore
#line (8,20)-(8,44) "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor"
FlexJustify.SpaceBetween

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(4, nameof(global::AntDesign.Flex.
#nullable restore
#line (8,46)-(8,51) "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor"
Align

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::OneOf.OneOf<global::AntDesign.FlexAlign, global::System.String>>(
#nullable restore
#line (8,53)-(8,69) "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor"
FlexAlign.Center

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(5, nameof(global::AntDesign.Flex.
#nullable restore
#line (8,71)-(8,76) "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor"
Style

#line default
#line hidden
#nullable disable
            ), "margin-bottom: 16px;");
            __builder.AddAttribute(6, "ChildContent", (global::Microsoft.AspNetCore.Components.RenderFragment)((__builder2) => {
                __builder2.OpenComponent<global::AntDesign.Title>(7);
                __builder2.AddComponentParameter(8, nameof(global::AntDesign.Title.
#nullable restore
#line (9,16)-(9,21) "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor"
Level

#line default
#line hidden
#nullable disable
                ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.Int32>(
#nullable restore
#line (9,23)-(9,24) "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor"
4

#line default
#line hidden
#nullable disable
                ));
                __builder2.AddComponentParameter(9, nameof(global::AntDesign.Title.
#nullable restore
#line (9,26)-(9,31) "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor"
Style

#line default
#line hidden
#nullable disable
                ), "margin: 0;");
                __builder2.AddAttribute(10, "ChildContent", (global::Microsoft.AspNetCore.Components.RenderFragment)((__builder3) => {
                    __builder3.AddMarkupContent(11, "接口探测");
                }
                ));
                __builder2.CloseComponent();
                __builder2.AddMarkupContent(12, "\n        ");
                __builder2.OpenComponent<global::AntDesign.Space>(13);
                __builder2.AddAttribute(14, "ChildContent", (global::Microsoft.AspNetCore.Components.RenderFragment)((__builder3) => {
                    __builder3.OpenComponent<global::AntDesign.SpaceItem>(15);
                    __builder3.AddAttribute(16, "ChildContent", (global::Microsoft.AspNetCore.Components.RenderFragment)((__builder4) => {
                        __builder4.OpenComponent<global::AntDesign.Button>(17);
                        __builder4.AddComponentParameter(18, nameof(global::AntDesign.Button.
#nullable restore
#line (12,25)-(12,29) "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor"
Type

#line default
#line hidden
#nullable disable
                        ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::AntDesign.ButtonType?>(
#nullable restore
#line (12,32)-(12,50) "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor"
ButtonType.Primary

#line default
#line hidden
#nullable disable
                        ));
                        __builder4.AddComponentParameter(19, nameof(global::AntDesign.Button.
#nullable restore
#line (12,52)-(12,56) "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor"
Size

#line default
#line hidden
#nullable disable
                        ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::AntDesign.ButtonSize>(
#nullable restore
#line (12,59)-(12,75) "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor"
ButtonSize.Small

#line default
#line hidden
#nullable disable
                        ));
                        __builder4.AddComponentParameter(20, nameof(global::AntDesign.Button.
#nullable restore
#line (12,77)-(12,81) "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor"
Icon

#line default
#line hidden
#nullable disable
                        ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.String>(
#nullable restore
#line (12,84)-(12,104) "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor"
IconType.Outline.Api

#line default
#line hidden
#nullable disable
                        ));
                        __builder4.AddComponentParameter(21, nameof(global::AntDesign.Button.
#nullable restore
#line (13,25)-(13,33) "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor"
Disabled

#line default
#line hidden
#nullable disable
                        ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.Boolean>(
#nullable restore
#line (13,37)-(13,51) "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor"
Module == null

#line default
#line hidden
#nullable disable
                        ));
                        __builder4.AddComponentParameter(22, nameof(global::AntDesign.Button.
#nullable restore
#line (13,54)-(13,61) "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor"
Loading

#line default
#line hidden
#nullable disable
                        ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.Boolean>(
#nullable restore
#line (13,64)-(13,75) "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor"
probingBase

#line default
#line hidden
#nullable disable
                        ));
                        __builder4.AddComponentParameter(23, nameof(global::AntDesign.Button.
#nullable restore
#line (13,77)-(13,84) "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor"
OnClick

#line default
#line hidden
#nullable disable
                        ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::Microsoft.AspNetCore.Components.EventCallback<global::Microsoft.AspNetCore.Components.Web.MouseEventArgs>>(global::Microsoft.AspNetCore.Components.EventCallback.Factory.Create<global::Microsoft.AspNetCore.Components.Web.MouseEventArgs>(this, 
#nullable restore
#line (13,86)-(13,98) "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor"
RunProbeBase

#line default
#line hidden
#nullable disable
                        )));
                        __builder4.AddAttribute(24, "ChildContent", (global::Microsoft.AspNetCore.Components.RenderFragment)((__builder5) => {
                            __builder5.AddMarkupContent(25, "\n                    探测接口\n                ");
                        }
                        ));
                        __builder4.CloseComponent();
                    }
                    ));
                    __builder3.CloseComponent();
                    __builder3.AddMarkupContent(26, "\n            ");
                    __builder3.OpenComponent<global::AntDesign.SpaceItem>(27);
                    __builder3.AddAttribute(28, "ChildContent", (global::Microsoft.AspNetCore.Components.RenderFragment)((__builder4) => {
                        __builder4.OpenComponent<global::AntDesign.Button>(29);
                        __builder4.AddComponentParameter(30, nameof(global::AntDesign.Button.
#nullable restore
#line (18,25)-(18,29) "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor"
Size

#line default
#line hidden
#nullable disable
                        ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::AntDesign.ButtonSize>(
#nullable restore
#line (18,32)-(18,48) "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor"
ButtonSize.Small

#line default
#line hidden
#nullable disable
                        ));
                        __builder4.AddComponentParameter(31, nameof(global::AntDesign.Button.
#nullable restore
#line (18,50)-(18,54) "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor"
Icon

#line default
#line hidden
#nullable disable
                        ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.String>(
#nullable restore
#line (18,57)-(18,87) "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor"
IconType.Outline.UnorderedList

#line default
#line hidden
#nullable disable
                        ));
                        __builder4.AddComponentParameter(32, nameof(global::AntDesign.Button.
#nullable restore
#line (19,25)-(19,33) "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor"
Disabled

#line default
#line hidden
#nullable disable
                        ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.Boolean>(
#nullable restore
#line (19,37)-(19,51) "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor"
Module == null

#line default
#line hidden
#nullable disable
                        ));
                        __builder4.AddComponentParameter(33, nameof(global::AntDesign.Button.
#nullable restore
#line (19,54)-(19,61) "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor"
Loading

#line default
#line hidden
#nullable disable
                        ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.Boolean>(
#nullable restore
#line (19,64)-(19,74) "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor"
probingAll

#line default
#line hidden
#nullable disable
                        ));
                        __builder4.AddComponentParameter(34, nameof(global::AntDesign.Button.
#nullable restore
#line (19,76)-(19,83) "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor"
OnClick

#line default
#line hidden
#nullable disable
                        ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::Microsoft.AspNetCore.Components.EventCallback<global::Microsoft.AspNetCore.Components.Web.MouseEventArgs>>(global::Microsoft.AspNetCore.Components.EventCallback.Factory.Create<global::Microsoft.AspNetCore.Components.Web.MouseEventArgs>(this, 
#nullable restore
#line (19,85)-(19,96) "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor"
RunProbeAll

#line default
#line hidden
#nullable disable
                        )));
                        __builder4.AddAttribute(35, "ChildContent", (global::Microsoft.AspNetCore.Components.RenderFragment)((__builder5) => {
                            __builder5.AddMarkupContent(36, "\n                    列出全部接口\n                ");
                        }
                        ));
                        __builder4.CloseComponent();
                    }
                    ));
                    __builder3.CloseComponent();
                }
                ));
                __builder2.CloseComponent();
            }
            ));
            __builder.CloseComponent();
#nullable restore
#line (26,1)-(26,5) "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor"
    

#line default
#line hidden
#nullable disable

#nullable restore
#line (26,6)-(28,1) "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor"
if (Module == null)
    {

#line default
#line hidden
#nullable disable

            __builder.OpenComponent<global::AntDesign.Text>(37);
            __builder.AddComponentParameter(38, nameof(global::AntDesign.Text.
#nullable restore
#line (28,25)-(28,29) "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor"
Type

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::AntDesign.TextElementType?>(
#nullable restore
#line (28,31)-(28,56) "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor"
TextElementType.Secondary

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(39, nameof(global::AntDesign.Text.
#nullable restore
#line (28,58)-(28,63) "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor"
Style

#line default
#line hidden
#nullable disable
            ), "display: block; margin-bottom: 8px;");
            __builder.AddAttribute(40, "ChildContent", (global::Microsoft.AspNetCore.Components.RenderFragment)((__builder2) => {
                __builder2.AddMarkupContent(41, "\n            角色激活后才能探测（探测走运行中的模块实例）。\n        ");
            }
            ));
            __builder.CloseComponent();
#nullable restore
#line (31,1)-(33,5) "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor"
    }

    

#line default
#line hidden
#nullable disable

#nullable restore
#line (33,34)-(34,1) "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor"


#line default
#line hidden
#nullable disable

            __builder.OpenComponent<global::AntDesign.Flex>(42);
            __builder.AddComponentParameter(43, nameof(global::AntDesign.Flex.
#nullable restore
#line (34,11)-(34,18) "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor"
Justify

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::OneOf.OneOf<global::AntDesign.FlexJustify, global::System.String>>(
#nullable restore
#line (34,20)-(34,44) "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor"
FlexJustify.SpaceBetween

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(44, nameof(global::AntDesign.Flex.
#nullable restore
#line (34,46)-(34,51) "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor"
Align

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::OneOf.OneOf<global::AntDesign.FlexAlign, global::System.String>>(
#nullable restore
#line (34,53)-(34,69) "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor"
FlexAlign.Center

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(45, nameof(global::AntDesign.Flex.
#nullable restore
#line (34,71)-(34,76) "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor"
Style

#line default
#line hidden
#nullable disable
            ), "margin-bottom: 12px;");
            __builder.AddAttribute(46, "ChildContent", (global::Microsoft.AspNetCore.Components.RenderFragment)((__builder2) => {
                __builder2.OpenComponent<global::AntDesign.Title>(47);
                __builder2.AddComponentParameter(48, nameof(global::AntDesign.Title.
#nullable restore
#line (35,16)-(35,21) "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor"
Level

#line default
#line hidden
#nullable disable
                ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.Int32>(
#nullable restore
#line (35,23)-(35,24) "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor"
4

#line default
#line hidden
#nullable disable
                ));
                __builder2.AddComponentParameter(49, nameof(global::AntDesign.Title.
#nullable restore
#line (35,26)-(35,31) "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor"
Style

#line default
#line hidden
#nullable disable
                ), "margin: 0;");
                __builder2.AddAttribute(50, "ChildContent", (global::Microsoft.AspNetCore.Components.RenderFragment)((__builder3) => {
                    __builder3.AddMarkupContent(51, "功能开关");
                }
                ));
                __builder2.CloseComponent();
                __builder2.AddMarkupContent(52, "\n        ");
                __builder2.OpenComponent<global::AntDesign.Text>(53);
                __builder2.AddComponentParameter(54, nameof(global::AntDesign.Text.
#nullable restore
#line (36,25)-(36,29) "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor"
Type

#line default
#line hidden
#nullable disable
                ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::AntDesign.TextElementType?>(
#nullable restore
#line (36,31)-(36,56) "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor"
TextElementType.Secondary

#line default
#line hidden
#nullable disable
                ));
                __builder2.AddAttribute(55, "ChildContent", (global::Microsoft.AspNetCore.Components.RenderFragment)((__builder3) => {
                    __builder3.AddMarkupContent(56, "关闭后AI无法使用对应功能，改动后记得保存");
                }
                ));
                __builder2.CloseComponent();
            }
            ));
            __builder.CloseComponent();
            __builder.AddMarkupContent(57, "\n    ");
            __builder.OpenElement(58, "div");
            __builder.AddAttribute(59, "style", "display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 12px 24px; margin-bottom: 20px;");
            __builder.OpenElement(60, "div");
            __builder.AddAttribute(61, "class", "sk-switch");
            __builder.OpenComponent<global::AntDesign.Switch>(62);
            __builder.AddComponentParameter(63, nameof(global::AntDesign.Switch.
#nullable restore
#line (40,27)-(40,32) "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor"
Value

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.Boolean>(
#nullable restore
#line (40,35)-(40,66) "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor"
Configuration.EnableSendArkCard

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(64, nameof(global::AntDesign.Switch.ValueChanged), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::Microsoft.AspNetCore.Components.EventCallback<global::System.Boolean>>(global::Microsoft.AspNetCore.Components.EventCallback.Factory.Create<global::System.Boolean>(this, global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.CreateInferredEventCallback(this, __value => Configuration.EnableSendArkCard = __value, Configuration.EnableSendArkCard))));
            __builder.AddComponentParameter(65, nameof(global::AntDesign.Switch.ValueExpression), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.Linq.Expressions.Expression<global::System.Func<global::System.Boolean>>>(() => Configuration.EnableSendArkCard));
            __builder.CloseComponent();
            __builder.AddMarkupContent(66, "\n            ");
            __builder.AddMarkupContent(67, "<div><div class=\"sk-name\">发音乐/视频卡片</div>\n                <div class=\"sk-desc\">SendArkCard：发音乐/视频分享卡到QQ，传歌名自动搜索，支持163/qq/bilibili/kugou</div></div>");
            __builder.CloseElement();
            __builder.AddMarkupContent(68, "\n        ");
            __builder.OpenElement(69, "div");
            __builder.AddAttribute(70, "class", "sk-switch");
            __builder.OpenComponent<global::AntDesign.Switch>(71);
            __builder.AddComponentParameter(72, nameof(global::AntDesign.Switch.
#nullable restore
#line (47,27)-(47,32) "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor"
Value

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.Boolean>(
#nullable restore
#line (47,35)-(47,68) "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor"
Configuration.EnableSendShareCard

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(73, nameof(global::AntDesign.Switch.ValueChanged), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::Microsoft.AspNetCore.Components.EventCallback<global::System.Boolean>>(global::Microsoft.AspNetCore.Components.EventCallback.Factory.Create<global::System.Boolean>(this, global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.CreateInferredEventCallback(this, __value => Configuration.EnableSendShareCard = __value, Configuration.EnableSendShareCard))));
            __builder.AddComponentParameter(74, nameof(global::AntDesign.Switch.ValueExpression), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.Linq.Expressions.Expression<global::System.Func<global::System.Boolean>>>(() => Configuration.EnableSendShareCard));
            __builder.CloseComponent();
            __builder.AddMarkupContent(75, "\n            ");
            __builder.AddMarkupContent(76, "<div><div class=\"sk-name\">发通用分享卡</div>\n                <div class=\"sk-desc\">SendShareCard：任意网页链接转分享卡，标题/描述/预览图自动抓取</div></div>");
            __builder.CloseElement();
            __builder.AddMarkupContent(77, "\n        ");
            __builder.OpenElement(78, "div");
            __builder.AddAttribute(79, "class", "sk-switch");
            __builder.OpenComponent<global::AntDesign.Switch>(80);
            __builder.AddComponentParameter(81, nameof(global::AntDesign.Switch.
#nullable restore
#line (54,27)-(54,32) "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor"
Value

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.Boolean>(
#nullable restore
#line (54,35)-(54,66) "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor"
Configuration.EnableSearchMusic

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(82, nameof(global::AntDesign.Switch.ValueChanged), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::Microsoft.AspNetCore.Components.EventCallback<global::System.Boolean>>(global::Microsoft.AspNetCore.Components.EventCallback.Factory.Create<global::System.Boolean>(this, global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.CreateInferredEventCallback(this, __value => Configuration.EnableSearchMusic = __value, Configuration.EnableSearchMusic))));
            __builder.AddComponentParameter(83, nameof(global::AntDesign.Switch.ValueExpression), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.Linq.Expressions.Expression<global::System.Func<global::System.Boolean>>>(() => Configuration.EnableSearchMusic));
            __builder.CloseComponent();
            __builder.AddMarkupContent(84, "\n            ");
            __builder.AddMarkupContent(85, "<div><div class=\"sk-name\">搜歌</div>\n                <div class=\"sk-desc\">SearchMusic：按关键词搜歌拿ID再发卡，支持163/qq/kugou</div></div>");
            __builder.CloseElement();
            __builder.AddMarkupContent(86, "\n        ");
            __builder.OpenElement(87, "div");
            __builder.AddAttribute(88, "class", "sk-switch");
            __builder.OpenComponent<global::AntDesign.Switch>(89);
            __builder.AddComponentParameter(90, nameof(global::AntDesign.Switch.
#nullable restore
#line (61,27)-(61,32) "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor"
Value

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.Boolean>(
#nullable restore
#line (61,35)-(61,65) "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor"
Configuration.EnableSearchBili

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(91, nameof(global::AntDesign.Switch.ValueChanged), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::Microsoft.AspNetCore.Components.EventCallback<global::System.Boolean>>(global::Microsoft.AspNetCore.Components.EventCallback.Factory.Create<global::System.Boolean>(this, global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.CreateInferredEventCallback(this, __value => Configuration.EnableSearchBili = __value, Configuration.EnableSearchBili))));
            __builder.AddComponentParameter(92, nameof(global::AntDesign.Switch.ValueExpression), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.Linq.Expressions.Expression<global::System.Func<global::System.Boolean>>>(() => Configuration.EnableSearchBili));
            __builder.CloseComponent();
            __builder.AddMarkupContent(93, "\n            ");
            __builder.AddMarkupContent(94, "<div><div class=\"sk-name\">B站搜索</div>\n                <div class=\"sk-desc\">SearchBili：搜B站视频拿BV号；配了第三方搜索接口走第三方，否则走B站官方</div></div>");
            __builder.CloseElement();
            __builder.AddMarkupContent(95, "\n        ");
            __builder.OpenElement(96, "div");
            __builder.AddAttribute(97, "class", "sk-switch");
            __builder.OpenComponent<global::AntDesign.Switch>(98);
            __builder.AddComponentParameter(99, nameof(global::AntDesign.Switch.
#nullable restore
#line (68,27)-(68,32) "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor"
Value

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.Boolean>(
#nullable restore
#line (68,35)-(68,64) "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor"
Configuration.EnableBiliParse

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(100, nameof(global::AntDesign.Switch.ValueChanged), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::Microsoft.AspNetCore.Components.EventCallback<global::System.Boolean>>(global::Microsoft.AspNetCore.Components.EventCallback.Factory.Create<global::System.Boolean>(this, global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.CreateInferredEventCallback(this, __value => Configuration.EnableBiliParse = __value, Configuration.EnableBiliParse))));
            __builder.AddComponentParameter(101, nameof(global::AntDesign.Switch.ValueExpression), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.Linq.Expressions.Expression<global::System.Func<global::System.Boolean>>>(() => Configuration.EnableBiliParse));
            __builder.CloseComponent();
            __builder.AddMarkupContent(102, "\n            ");
            __builder.AddMarkupContent(103, "<div><div class=\"sk-name\">B站链接解析</div>\n                <div class=\"sk-desc\">BiliParse：解析B站链接（视频/短链/专栏/番剧/直播间），可取播放直链</div></div>");
            __builder.CloseElement();
            __builder.AddMarkupContent(104, "\n        ");
            __builder.OpenElement(105, "div");
            __builder.AddAttribute(106, "class", "sk-switch");
            __builder.OpenComponent<global::AntDesign.Switch>(107);
            __builder.AddComponentParameter(108, nameof(global::AntDesign.Switch.
#nullable restore
#line (75,27)-(75,32) "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor"
Value

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.Boolean>(
#nullable restore
#line (75,35)-(75,67) "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor"
Configuration.EnableBiliUserInfo

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(109, nameof(global::AntDesign.Switch.ValueChanged), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::Microsoft.AspNetCore.Components.EventCallback<global::System.Boolean>>(global::Microsoft.AspNetCore.Components.EventCallback.Factory.Create<global::System.Boolean>(this, global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.CreateInferredEventCallback(this, __value => Configuration.EnableBiliUserInfo = __value, Configuration.EnableBiliUserInfo))));
            __builder.AddComponentParameter(110, nameof(global::AntDesign.Switch.ValueExpression), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.Linq.Expressions.Expression<global::System.Func<global::System.Boolean>>>(() => Configuration.EnableBiliUserInfo));
            __builder.CloseComponent();
            __builder.AddMarkupContent(111, "\n            ");
            __builder.AddMarkupContent(112, "<div><div class=\"sk-name\">B站用户查询</div>\n                <div class=\"sk-desc\">BiliUserInfo：按UID查昵称、等级、粉丝数、签名、认证、投稿数</div></div>");
            __builder.CloseElement();
            __builder.AddMarkupContent(113, "\n        ");
            __builder.OpenElement(114, "div");
            __builder.AddAttribute(115, "class", "sk-switch");
            __builder.OpenComponent<global::AntDesign.Switch>(116);
            __builder.AddComponentParameter(117, nameof(global::AntDesign.Switch.
#nullable restore
#line (82,27)-(82,32) "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor"
Value

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.Boolean>(
#nullable restore
#line (82,35)-(82,66) "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor"
Configuration.EnableBiliUpdates

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(118, nameof(global::AntDesign.Switch.ValueChanged), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::Microsoft.AspNetCore.Components.EventCallback<global::System.Boolean>>(global::Microsoft.AspNetCore.Components.EventCallback.Factory.Create<global::System.Boolean>(this, global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.CreateInferredEventCallback(this, __value => Configuration.EnableBiliUpdates = __value, Configuration.EnableBiliUpdates))));
            __builder.AddComponentParameter(119, nameof(global::AntDesign.Switch.ValueExpression), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.Linq.Expressions.Expression<global::System.Func<global::System.Boolean>>>(() => Configuration.EnableBiliUpdates));
            __builder.CloseComponent();
            __builder.AddMarkupContent(120, "\n            ");
            __builder.AddMarkupContent(121, "<div><div class=\"sk-name\">UP主更新查询</div>\n                <div class=\"sk-desc\">BiliUpdates：查UP主最新动态/视频/专栏，视频带BV号可直接发卡</div></div>");
            __builder.CloseElement();
            __builder.AddMarkupContent(122, "\n        ");
            __builder.OpenElement(123, "div");
            __builder.AddAttribute(124, "class", "sk-switch");
            __builder.OpenComponent<global::AntDesign.Switch>(125);
            __builder.AddComponentParameter(126, nameof(global::AntDesign.Switch.
#nullable restore
#line (89,27)-(89,32) "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor"
Value

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.Boolean>(
#nullable restore
#line (89,35)-(89,62) "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor"
Configuration.EnableBiliHot

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(127, nameof(global::AntDesign.Switch.ValueChanged), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::Microsoft.AspNetCore.Components.EventCallback<global::System.Boolean>>(global::Microsoft.AspNetCore.Components.EventCallback.Factory.Create<global::System.Boolean>(this, global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.CreateInferredEventCallback(this, __value => Configuration.EnableBiliHot = __value, Configuration.EnableBiliHot))));
            __builder.AddComponentParameter(128, nameof(global::AntDesign.Switch.ValueExpression), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.Linq.Expressions.Expression<global::System.Func<global::System.Boolean>>>(() => Configuration.EnableBiliHot));
            __builder.CloseComponent();
            __builder.AddMarkupContent(129, "\n            ");
            __builder.AddMarkupContent(130, "<div><div class=\"sk-name\">B站热门/相关</div>\n                <div class=\"sk-desc\">BiliHot：B站热门视频榜，或某个视频的相关推荐</div></div>");
            __builder.CloseElement();
            __builder.AddMarkupContent(131, "\n        ");
            __builder.OpenElement(132, "div");
            __builder.AddAttribute(133, "class", "sk-switch");
            __builder.OpenComponent<global::AntDesign.Switch>(134);
            __builder.AddComponentParameter(135, nameof(global::AntDesign.Switch.
#nullable restore
#line (96,27)-(96,32) "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor"
Value

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.Boolean>(
#nullable restore
#line (96,35)-(96,66) "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor"
Configuration.EnableBiliQrLogin

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(136, nameof(global::AntDesign.Switch.ValueChanged), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::Microsoft.AspNetCore.Components.EventCallback<global::System.Boolean>>(global::Microsoft.AspNetCore.Components.EventCallback.Factory.Create<global::System.Boolean>(this, global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.CreateInferredEventCallback(this, __value => Configuration.EnableBiliQrLogin = __value, Configuration.EnableBiliQrLogin))));
            __builder.AddComponentParameter(137, nameof(global::AntDesign.Switch.ValueExpression), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.Linq.Expressions.Expression<global::System.Func<global::System.Boolean>>>(() => Configuration.EnableBiliQrLogin));
            __builder.CloseComponent();
            __builder.AddMarkupContent(138, "\n            ");
            __builder.AddMarkupContent(139, "<div><div class=\"sk-name\">B站扫码登录</div>\n                <div class=\"sk-desc\">BiliQrLogin：申请二维码给人扫、轮询登录状态，成功得cookie_id</div></div>");
            __builder.CloseElement();
            __builder.AddMarkupContent(140, "\n        ");
            __builder.OpenElement(141, "div");
            __builder.AddAttribute(142, "class", "sk-switch");
            __builder.OpenComponent<global::AntDesign.Switch>(143);
            __builder.AddComponentParameter(144, nameof(global::AntDesign.Switch.
#nullable restore
#line (103,27)-(103,32) "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor"
Value

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.Boolean>(
#nullable restore
#line (103,35)-(103,72) "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor"
Configuration.EnableBiliCookieRefresh

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(145, nameof(global::AntDesign.Switch.ValueChanged), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::Microsoft.AspNetCore.Components.EventCallback<global::System.Boolean>>(global::Microsoft.AspNetCore.Components.EventCallback.Factory.Create<global::System.Boolean>(this, global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.CreateInferredEventCallback(this, __value => Configuration.EnableBiliCookieRefresh = __value, Configuration.EnableBiliCookieRefresh))));
            __builder.AddComponentParameter(146, nameof(global::AntDesign.Switch.ValueExpression), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.Linq.Expressions.Expression<global::System.Func<global::System.Boolean>>>(() => Configuration.EnableBiliCookieRefresh));
            __builder.CloseComponent();
            __builder.AddMarkupContent(147, "\n            ");
            __builder.AddMarkupContent(148, "<div><div class=\"sk-name\">Cookie刷新</div>\n                <div class=\"sk-desc\">BiliCookieRefresh：刷新/检查B站登录Cookie，延长有效期</div></div>");
            __builder.CloseElement();
            __builder.AddMarkupContent(149, "\n        ");
            __builder.OpenElement(150, "div");
            __builder.AddAttribute(151, "class", "sk-switch");
            __builder.OpenComponent<global::AntDesign.Switch>(152);
            __builder.AddComponentParameter(153, nameof(global::AntDesign.Switch.
#nullable restore
#line (110,27)-(110,32) "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor"
Value

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.Boolean>(
#nullable restore
#line (110,35)-(110,65) "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor"
Configuration.EnableBiliCookie

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(154, nameof(global::AntDesign.Switch.ValueChanged), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::Microsoft.AspNetCore.Components.EventCallback<global::System.Boolean>>(global::Microsoft.AspNetCore.Components.EventCallback.Factory.Create<global::System.Boolean>(this, global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.CreateInferredEventCallback(this, __value => Configuration.EnableBiliCookie = __value, Configuration.EnableBiliCookie))));
            __builder.AddComponentParameter(155, nameof(global::AntDesign.Switch.ValueExpression), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.Linq.Expressions.Expression<global::System.Func<global::System.Boolean>>>(() => Configuration.EnableBiliCookie));
            __builder.CloseComponent();
            __builder.AddMarkupContent(156, "\n            ");
            __builder.AddMarkupContent(157, "<div><div class=\"sk-name\">Cookie管理</div>\n                <div class=\"sk-desc\">BiliCookie：登录Cookie的列出/验证/删除/导入；不提供导出，避免凭据进聊天记录</div></div>");
            __builder.CloseElement();
            __builder.AddMarkupContent(158, "\n        ");
            __builder.OpenElement(159, "div");
            __builder.AddAttribute(160, "class", "sk-switch");
            __builder.OpenComponent<global::AntDesign.Switch>(161);
            __builder.AddComponentParameter(162, nameof(global::AntDesign.Switch.
#nullable restore
#line (117,27)-(117,32) "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor"
Value

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.Boolean>(
#nullable restore
#line (117,35)-(117,63) "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor"
Configuration.EnableIpLookup

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(163, nameof(global::AntDesign.Switch.ValueChanged), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::Microsoft.AspNetCore.Components.EventCallback<global::System.Boolean>>(global::Microsoft.AspNetCore.Components.EventCallback.Factory.Create<global::System.Boolean>(this, global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.CreateInferredEventCallback(this, __value => Configuration.EnableIpLookup = __value, Configuration.EnableIpLookup))));
            __builder.AddComponentParameter(164, nameof(global::AntDesign.Switch.ValueExpression), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.Linq.Expressions.Expression<global::System.Func<global::System.Boolean>>>(() => Configuration.EnableIpLookup));
            __builder.CloseComponent();
            __builder.AddMarkupContent(165, "\n            ");
            __builder.AddMarkupContent(166, "<div><div class=\"sk-name\">IP查询</div>\n                <div class=\"sk-desc\">IpLookup：查IP的归属地/运营商/ASN/时区，不填查本机出口IP</div></div>");
            __builder.CloseElement();
            __builder.AddMarkupContent(167, "\n        ");
            __builder.OpenElement(168, "div");
            __builder.AddAttribute(169, "class", "sk-switch");
            __builder.OpenComponent<global::AntDesign.Switch>(170);
            __builder.AddComponentParameter(171, nameof(global::AntDesign.Switch.
#nullable restore
#line (124,27)-(124,32) "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor"
Value

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.Boolean>(
#nullable restore
#line (124,35)-(124,71) "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor"
Configuration.EnableOfficialFallback

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(172, nameof(global::AntDesign.Switch.ValueChanged), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::Microsoft.AspNetCore.Components.EventCallback<global::System.Boolean>>(global::Microsoft.AspNetCore.Components.EventCallback.Factory.Create<global::System.Boolean>(this, global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.CreateInferredEventCallback(this, __value => Configuration.EnableOfficialFallback = __value, Configuration.EnableOfficialFallback))));
            __builder.AddComponentParameter(173, nameof(global::AntDesign.Switch.ValueExpression), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.Linq.Expressions.Expression<global::System.Func<global::System.Boolean>>>(() => Configuration.EnableOfficialFallback));
            __builder.CloseComponent();
            __builder.AddMarkupContent(174, "\n            ");
            __builder.AddMarkupContent(175, "<div><div class=\"sk-name\">官方接口容灾</div>\n                <div class=\"sk-desc\">第三方接口失败时自动切换官方公开接口（音乐卡官方音乐段/搜索平台公开接口/B站系列B站web接口）</div></div>");
            __builder.CloseElement();
            __builder.AddMarkupContent(176, "\n        ");
            __builder.OpenElement(177, "div");
            __builder.AddAttribute(178, "class", "sk-switch");
            __builder.OpenComponent<global::AntDesign.Switch>(179);
            __builder.AddComponentParameter(180, nameof(global::AntDesign.Switch.
#nullable restore
#line (131,27)-(131,32) "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor"
Value

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.Boolean>(
#nullable restore
#line (131,35)-(131,64) "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor"
Configuration.EnableProbeBase

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(181, nameof(global::AntDesign.Switch.ValueChanged), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::Microsoft.AspNetCore.Components.EventCallback<global::System.Boolean>>(global::Microsoft.AspNetCore.Components.EventCallback.Factory.Create<global::System.Boolean>(this, global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.CreateInferredEventCallback(this, __value => Configuration.EnableProbeBase = __value, Configuration.EnableProbeBase))));
            __builder.AddComponentParameter(182, nameof(global::AntDesign.Switch.ValueExpression), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.Linq.Expressions.Expression<global::System.Func<global::System.Boolean>>>(() => Configuration.EnableProbeBase));
            __builder.CloseComponent();
            __builder.AddMarkupContent(183, "\n            ");
            __builder.AddMarkupContent(184, "<div><div class=\"sk-name\">探测接口</div>\n                <div class=\"sk-desc\">ProbeBase：实测音乐卡/分享卡/歌曲搜索接口通不通，换第三方先跑一次</div></div>");
            __builder.CloseElement();
            __builder.AddMarkupContent(185, "\n        ");
            __builder.OpenElement(186, "div");
            __builder.AddAttribute(187, "class", "sk-switch");
            __builder.OpenComponent<global::AntDesign.Switch>(188);
            __builder.AddComponentParameter(189, nameof(global::AntDesign.Switch.
#nullable restore
#line (138,27)-(138,32) "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor"
Value

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.Boolean>(
#nullable restore
#line (138,35)-(138,63) "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor"
Configuration.EnableProbeAll

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(190, nameof(global::AntDesign.Switch.ValueChanged), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::Microsoft.AspNetCore.Components.EventCallback<global::System.Boolean>>(global::Microsoft.AspNetCore.Components.EventCallback.Factory.Create<global::System.Boolean>(this, global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.CreateInferredEventCallback(this, __value => Configuration.EnableProbeAll = __value, Configuration.EnableProbeAll))));
            __builder.AddComponentParameter(191, nameof(global::AntDesign.Switch.ValueExpression), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.Linq.Expressions.Expression<global::System.Func<global::System.Boolean>>>(() => Configuration.EnableProbeAll));
            __builder.CloseComponent();
            __builder.AddMarkupContent(192, "\n            ");
            __builder.AddMarkupContent(193, "<div><div class=\"sk-name\">列出全部接口</div>\n                <div class=\"sk-desc\">ProbeAll：列出基地址下发现的所有接口，只列举不调用不耗次数</div></div>");
            __builder.CloseElement();
            __builder.CloseElement();
            __builder.AddMarkupContent(194, "\n\n    ");
            __builder.OpenComponent<global::AntDesign.Title>(195);
            __builder.AddComponentParameter(196, nameof(global::AntDesign.Title.
#nullable restore
#line (147,12)-(147,17) "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor"
Level

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.Int32>(
#nullable restore
#line (147,19)-(147,20) "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor"
4

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(197, nameof(global::AntDesign.Title.
#nullable restore
#line (147,22)-(147,27) "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor"
Style

#line default
#line hidden
#nullable disable
            ), "margin: 0 0 12px 0;");
            __builder.AddAttribute(198, "ChildContent", (global::Microsoft.AspNetCore.Components.RenderFragment)((__builder2) => {
                __builder2.AddMarkupContent(199, "接口配置");
            }
            ));
            __builder.CloseComponent();
            __builder.AddMarkupContent(200, "\n    ");
            __builder.OpenComponent<global::AntDesign.Form<
#nullable restore
#line (148,19)-(148,33) "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor"
ShareArkConfig

#line default
#line hidden
#nullable disable
            >>(201);
            __builder.AddComponentParameter(202, nameof(global::AntDesign.Form<ShareArkConfig>.
#nullable restore
#line (148,35)-(148,40) "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor"
Model

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<ShareArkConfig>(
#nullable restore
#line (148,43)-(148,56) "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor"
Configuration

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(203, nameof(global::AntDesign.Form<ShareArkConfig>.
#nullable restore
#line (148,58)-(148,64) "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor"
Layout

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::AntDesign.FormLayout>(
#nullable restore
#line (148,67)-(148,86) "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor"
FormLayout.Vertical

#line default
#line hidden
#nullable disable
            ));
            __builder.AddAttribute(204, "ChildContent", (global::Microsoft.AspNetCore.Components.RenderFragment<ShareArkConfig>)((context) => (__builder2) => {
                __builder2.OpenComponent<global::AntDesign.FormItem>(205);
                __builder2.AddComponentParameter(206, nameof(global::AntDesign.FormItem.
#nullable restore
#line (149,19)-(149,24) "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor"
Label

#line default
#line hidden
#nullable disable
                ), "第三方接口基地址");
                __builder2.AddAttribute(207, "ChildContent", (global::Microsoft.AspNetCore.Components.RenderFragment)((__builder3) => {
                    global::__Blazor.Suran.ShareArk.ShareArkUI.TypeInference.CreateInput_0(__builder3, 208, 209, "如 https://apii.xianyuw.cn/api/v1，填一个就能用", 210, 
#nullable restore
#line (150,34)-(150,55) "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor"
Configuration.BaseUrl

#line default
#line hidden
#nullable disable
                    , 211, global::Microsoft.AspNetCore.Components.EventCallback.Factory.Create(this, global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.CreateInferredEventCallback(this, __value => Configuration.BaseUrl = __value, Configuration.BaseUrl)), 212, () => Configuration.BaseUrl);
                    __builder3.AddMarkupContent(213, "\n            ");
                    __builder3.OpenComponent<global::AntDesign.Text>(214);
                    __builder3.AddComponentParameter(215, nameof(global::AntDesign.Text.
#nullable restore
#line (151,29)-(151,33) "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor"
Type

#line default
#line hidden
#nullable disable
                    ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::AntDesign.TextElementType?>(
#nullable restore
#line (151,35)-(151,60) "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor"
TextElementType.Secondary

#line default
#line hidden
#nullable disable
                    ));
                    __builder3.AddComponentParameter(216, nameof(global::AntDesign.Text.
#nullable restore
#line (151,62)-(151,67) "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor"
Style

#line default
#line hidden
#nullable disable
                    ), "font-size: 11px;");
                    __builder3.AddAttribute(217, "ChildContent", (global::Microsoft.AspNetCore.Components.RenderFragment)((__builder4) => {
                        __builder4.AddMarkupContent(218, "\n                音乐卡/分享卡/歌曲搜索接口地址会自动适配；咸鱼API到 https://apii.xianyuw.cn 注册拿key\n            ");
                    }
                    ));
                    __builder3.CloseComponent();
                }
                ));
                __builder2.CloseComponent();
                __builder2.AddMarkupContent(219, "\n        ");
                __builder2.OpenComponent<global::AntDesign.FormItem>(220);
                __builder2.AddComponentParameter(221, nameof(global::AntDesign.FormItem.
#nullable restore
#line (155,19)-(155,24) "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor"
Label

#line default
#line hidden
#nullable disable
                ), "接口Token");
                __builder2.AddAttribute(222, "ChildContent", (global::Microsoft.AspNetCore.Components.RenderFragment)((__builder3) => {
                    __builder3.OpenComponent<global::AntDesign.InputPassword>(223);
                    __builder3.AddComponentParameter(224, nameof(global::AntDesign.InputPassword.
#nullable restore
#line (156,64)-(156,75) "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor"
Placeholder

#line default
#line hidden
#nullable disable
                    ), "第三方接口凭证key，可留空");
                    __builder3.AddComponentParameter(225, nameof(global::AntDesign.InputPassword.
#nullable restore
#line (156,34)-(156,39) "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor"
Value

#line default
#line hidden
#nullable disable
                    ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.String>(
#nullable restore
#line (156,42)-(156,62) "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor"
Configuration.ApiKey

#line default
#line hidden
#nullable disable
                    ));
                    __builder3.AddComponentParameter(226, nameof(global::AntDesign.InputPassword.ValueChanged), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::Microsoft.AspNetCore.Components.EventCallback<global::System.String>>(global::Microsoft.AspNetCore.Components.EventCallback.Factory.Create<global::System.String>(this, global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.CreateInferredEventCallback(this, __value => Configuration.ApiKey = __value, Configuration.ApiKey))));
                    __builder3.AddComponentParameter(227, nameof(global::AntDesign.InputPassword.ValueExpression), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.Linq.Expressions.Expression<global::System.Func<global::System.String>>>(() => Configuration.ApiKey));
                    __builder3.CloseComponent();
                }
                ));
                __builder2.CloseComponent();
                __builder2.AddMarkupContent(228, "\n        ");
                __builder2.OpenComponent<global::AntDesign.FormItem>(229);
                __builder2.AddComponentParameter(230, nameof(global::AntDesign.FormItem.
#nullable restore
#line (158,19)-(158,24) "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor"
Label

#line default
#line hidden
#nullable disable
                ), "协议端地址");
                __builder2.AddAttribute(231, "ChildContent", (global::Microsoft.AspNetCore.Components.RenderFragment)((__builder3) => {
                    global::__Blazor.Suran.ShareArk.ShareArkUI.TypeInference.CreateInput_1(__builder3, 232, 233, "OneBot正向WebSocket，默认 ws://127.0.0.1:3001", 234, 
#nullable restore
#line (159,34)-(159,53) "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor"
Configuration.WsUrl

#line default
#line hidden
#nullable disable
                    , 235, global::Microsoft.AspNetCore.Components.EventCallback.Factory.Create(this, global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.CreateInferredEventCallback(this, __value => Configuration.WsUrl = __value, Configuration.WsUrl)), 236, () => Configuration.WsUrl);
                }
                ));
                __builder2.CloseComponent();
                __builder2.AddMarkupContent(237, "\n\n        ");
                __builder2.OpenComponent<global::AntDesign.Divider>(238);
                __builder2.AddAttribute(239, "ChildContent", (global::Microsoft.AspNetCore.Components.RenderFragment)((__builder3) => {
                    __builder3.AddMarkupContent(240, "手动指定接口地址（可留空，留空走自动探测）");
                }
                ));
                __builder2.CloseComponent();
                __builder2.AddMarkupContent(241, "\n        ");
                __builder2.OpenComponent<global::AntDesign.FormItem>(242);
                __builder2.AddComponentParameter(243, nameof(global::AntDesign.FormItem.
#nullable restore
#line (163,19)-(163,24) "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor"
Label

#line default
#line hidden
#nullable disable
                ), "音乐卡签名接口地址");
                __builder2.AddAttribute(244, "ChildContent", (global::Microsoft.AspNetCore.Components.RenderFragment)((__builder3) => {
                    global::__Blazor.Suran.ShareArk.ShareArkUI.TypeInference.CreateInput_2(__builder3, 245, 246, "完整地址；自带query参数也可以", 247, 
#nullable restore
#line (164,34)-(164,59) "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor"
Configuration.MusicArkUrl

#line default
#line hidden
#nullable disable
                    , 248, global::Microsoft.AspNetCore.Components.EventCallback.Factory.Create(this, global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.CreateInferredEventCallback(this, __value => Configuration.MusicArkUrl = __value, Configuration.MusicArkUrl)), 249, () => Configuration.MusicArkUrl);
                }
                ));
                __builder2.CloseComponent();
                __builder2.AddMarkupContent(250, "\n        ");
                __builder2.OpenComponent<global::AntDesign.FormItem>(251);
                __builder2.AddComponentParameter(252, nameof(global::AntDesign.FormItem.
#nullable restore
#line (166,19)-(166,24) "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor"
Label

#line default
#line hidden
#nullable disable
                ), "分享卡签名接口地址");
                __builder2.AddAttribute(253, "ChildContent", (global::Microsoft.AspNetCore.Components.RenderFragment)((__builder3) => {
                    global::__Blazor.Suran.ShareArk.ShareArkUI.TypeInference.CreateInput_3(__builder3, 254, 255, "完整地址；自带query参数也可以", 256, 
#nullable restore
#line (167,34)-(167,59) "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor"
Configuration.ShareArkUrl

#line default
#line hidden
#nullable disable
                    , 257, global::Microsoft.AspNetCore.Components.EventCallback.Factory.Create(this, global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.CreateInferredEventCallback(this, __value => Configuration.ShareArkUrl = __value, Configuration.ShareArkUrl)), 258, () => Configuration.ShareArkUrl);
                }
                ));
                __builder2.CloseComponent();
                __builder2.AddMarkupContent(259, "\n        ");
                __builder2.OpenComponent<global::AntDesign.FormItem>(260);
                __builder2.AddComponentParameter(261, nameof(global::AntDesign.FormItem.
#nullable restore
#line (169,19)-(169,24) "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor"
Label

#line default
#line hidden
#nullable disable
                ), "歌曲搜索接口地址");
                __builder2.AddAttribute(262, "ChildContent", (global::Microsoft.AspNetCore.Components.RenderFragment)((__builder3) => {
                    global::__Blazor.Suran.ShareArk.ShareArkUI.TypeInference.CreateInput_4(__builder3, 263, 264, "可含 {pf} 占位符，替换为163/qq/kugou", 265, 
#nullable restore
#line (170,34)-(170,57) "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor"
Configuration.SearchUrl

#line default
#line hidden
#nullable disable
                    , 266, global::Microsoft.AspNetCore.Components.EventCallback.Factory.Create(this, global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.CreateInferredEventCallback(this, __value => Configuration.SearchUrl = __value, Configuration.SearchUrl)), 267, () => Configuration.SearchUrl);
                }
                ));
                __builder2.CloseComponent();
                __builder2.AddMarkupContent(268, "\n        ");
                __builder2.OpenComponent<global::AntDesign.FormItem>(269);
                __builder2.AddComponentParameter(270, nameof(global::AntDesign.FormItem.
#nullable restore
#line (172,19)-(172,24) "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor"
Label

#line default
#line hidden
#nullable disable
                ), "B站搜索接口地址");
                __builder2.AddAttribute(271, "ChildContent", (global::Microsoft.AspNetCore.Components.RenderFragment)((__builder3) => {
                    global::__Blazor.Suran.ShareArk.ShareArkUI.TypeInference.CreateInput_5(__builder3, 272, 273, "可留空，留空走B站官方接口", 274, 
#nullable restore
#line (173,34)-(173,61) "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor"
Configuration.BiliSearchUrl

#line default
#line hidden
#nullable disable
                    , 275, global::Microsoft.AspNetCore.Components.EventCallback.Factory.Create(this, global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.CreateInferredEventCallback(this, __value => Configuration.BiliSearchUrl = __value, Configuration.BiliSearchUrl)), 276, () => Configuration.BiliSearchUrl);
                }
                ));
                __builder2.CloseComponent();
            }
            ));
            __builder.CloseComponent();
            __builder.AddMarkupContent(277, "\n\n    ");
            __builder.OpenComponent<global::AntDesign.Modal>(278);
            __builder.AddComponentParameter(279, nameof(global::AntDesign.Modal.
#nullable restore
#line (178,12)-(178,17) "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor"
Title

#line default
#line hidden
#nullable disable
            ), "探测结果");
            __builder.AddComponentParameter(280, nameof(global::AntDesign.Modal.
#nullable restore
#line (179,12)-(179,19) "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor"
Visible

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::System.Boolean>(
#nullable restore
#line (179,22)-(179,42) "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor"
isReportModalVisible

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(281, nameof(global::AntDesign.Modal.
#nullable restore
#line (180,12)-(180,20) "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor"
OnCancel

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::Microsoft.AspNetCore.Components.EventCallback<global::Microsoft.AspNetCore.Components.Web.MouseEventArgs>>(global::Microsoft.AspNetCore.Components.EventCallback.Factory.Create<global::Microsoft.AspNetCore.Components.Web.MouseEventArgs>(this, 
#nullable restore
#line (180,24)-(180,58) "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor"
() => isReportModalVisible = false

#line default
#line hidden
#nullable disable
            )));
            __builder.AddComponentParameter(282, nameof(global::AntDesign.Modal.
#nullable restore
#line (181,12)-(181,18) "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor"
Footer

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::OneOf.OneOf<global::System.String, global::Microsoft.AspNetCore.Components.RenderFragment>?>(
#nullable restore
#line (181,20)-(181,24) "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor"
null

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(283, nameof(global::AntDesign.Modal.
#nullable restore
#line (182,12)-(182,17) "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor"
Width

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::OneOf.OneOf<global::System.String, global::System.Double>>(
#nullable restore
#line (182,19)-(182,22) "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor"
640

#line default
#line hidden
#nullable disable
            ));
            __builder.AddAttribute(284, "ChildContent", (global::Microsoft.AspNetCore.Components.RenderFragment)((__builder2) => {
                __builder2.OpenElement(285, "div");
                __builder2.AddAttribute(286, "style", "max-height: 460px; overflow-y: auto; background: #f6f8fa; padding: 10px; border-radius: 6px; border: 1px solid #e8e8e8; font-family: monospace; font-size: 12px; white-space: pre-wrap; word-break: break-word;");
#nullable restore
#line (183,231)-(183,237) 27 "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor"
__builder2.AddContent(287, report

#line default
#line hidden
#nullable disable
                );
                __builder2.CloseElement();
            }
            ));
            __builder.CloseComponent();
            __builder.CloseElement();
            __builder.AddMarkupContent(288, "\n\n");
            __builder.AddMarkupContent(289, @"<style>
    .sk-switch {
        display: flex;
        align-items: flex-start;
        gap: 10px;
    }

        .sk-switch .ant-switch {
            margin-top: 3px;
            flex-shrink: 0;
        }

    .sk-name {
        font-size: 13px;
        font-weight: 600;
        line-height: 20px;
    }

    .sk-desc {
        font-size: 11px;
        color: #8c8c8c;
        line-height: 1.5;
        margin-top: 1px;
    }
</style>");
        }
        #pragma warning restore 1998
#nullable restore
#line (213,8)-(291,1) "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor"

    bool probingBase;
    bool probingAll;
    bool isReportModalVisible;
    string? report;

    // 参考OpenAI插件：先校验配置再探测，结果用弹窗展示，反馈用消息气泡
    bool HasAnyApiConfig() =>
        !string.IsNullOrWhiteSpace(Configuration.BaseUrl)
        || !string.IsNullOrWhiteSpace(Configuration.MusicArkUrl)
        || !string.IsNullOrWhiteSpace(Configuration.ShareArkUrl)
        || !string.IsNullOrWhiteSpace(Configuration.SearchUrl);

    async Task RunProbeBase()
    {
        if (Module == null)
        {
            await MessageService.WarningAsync("角色激活后才能探测喵！");
            return;
        }
        if (!HasAnyApiConfig())
        {
            await MessageService.WarningAsync("请先填写第三方接口基地址或手动接口地址喵！");
            return;
        }

        probingBase = true;
        try
        {
            report = await Module.ProbeBaseReportAsync();
            isReportModalVisible = true;
            await MessageService.SuccessAsync("探测完成喵！");
        }
        catch (Exception ex)
        {
            report = ex.Message;
            isReportModalVisible = true;
            await MessageService.ErrorAsync($"探测失败: {ex.Message}");
        }
        finally
        {
            probingBase = false;
            StateHasChanged();
        }
    }

    async Task RunProbeAll()
    {
        if (Module == null)
        {
            await MessageService.WarningAsync("角色激活后才能探测喵！");
            return;
        }
        if (string.IsNullOrWhiteSpace(Configuration.BaseUrl))
        {
            await MessageService.WarningAsync("列出全部接口需要先填写第三方接口基地址喵！");
            return;
        }

        probingAll = true;
        try
        {
            report = await Module.ProbeAllReportAsync();
            isReportModalVisible = true;
            await MessageService.SuccessAsync("列举完成喵！");
        }
        catch (Exception ex)
        {
            report = ex.Message;
            isReportModalVisible = true;
            await MessageService.ErrorAsync($"列举失败: {ex.Message}");
        }
        finally
        {
            probingAll = false;
            StateHasChanged();
        }
    }

#line default
#line hidden
#nullable disable

        [global::Microsoft.AspNetCore.Components.InjectAttribute] private 
#nullable restore
#line (4,9)-(4,24) "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor"
IMessageService

#line default
#line hidden
#nullable disable
         
#nullable restore
#line (4,25)-(4,39) "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor"
MessageService

#line default
#line hidden
#nullable disable
         { get; set; }
         = default!;
    }
}
namespace __Blazor.Suran.ShareArk.ShareArkUI
{
    #line hidden
    internal static class TypeInference
    {
        public static void CreateInput_0<TValue>(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder, int seq, int __seq0, global::System.String __arg0, int __seq1, TValue __arg1, int __seq2, global::Microsoft.AspNetCore.Components.EventCallback<TValue> __arg2, int __seq3, global::System.Linq.Expressions.Expression<global::System.Func<TValue>> __arg3)
        {
        __builder.OpenComponent<global::AntDesign.Input<TValue>>(seq);
        __builder.AddComponentParameter(__seq0, nameof(global::AntDesign.Input<TValue>.
#nullable restore
#line (150,57)-(150,68) "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor"
Placeholder

#line default
#line hidden
#nullable disable
        ), __arg0);
        __builder.AddComponentParameter(__seq1, nameof(global::AntDesign.Input<TValue>.
#nullable restore
#line (150,26)-(150,31) "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor"
Value

#line default
#line hidden
#nullable disable
        ), __arg1);
        __builder.AddComponentParameter(__seq2, nameof(global::AntDesign.Input<TValue>.ValueChanged), __arg2);
        __builder.AddComponentParameter(__seq3, nameof(global::AntDesign.Input<TValue>.ValueExpression), __arg3);
        __builder.CloseComponent();
        }
        public static void CreateInput_1<TValue>(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder, int seq, int __seq0, global::System.String __arg0, int __seq1, TValue __arg1, int __seq2, global::Microsoft.AspNetCore.Components.EventCallback<TValue> __arg2, int __seq3, global::System.Linq.Expressions.Expression<global::System.Func<TValue>> __arg3)
        {
        __builder.OpenComponent<global::AntDesign.Input<TValue>>(seq);
        __builder.AddComponentParameter(__seq0, nameof(global::AntDesign.Input<TValue>.
#nullable restore
#line (159,55)-(159,66) "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor"
Placeholder

#line default
#line hidden
#nullable disable
        ), __arg0);
        __builder.AddComponentParameter(__seq1, nameof(global::AntDesign.Input<TValue>.
#nullable restore
#line (159,26)-(159,31) "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor"
Value

#line default
#line hidden
#nullable disable
        ), __arg1);
        __builder.AddComponentParameter(__seq2, nameof(global::AntDesign.Input<TValue>.ValueChanged), __arg2);
        __builder.AddComponentParameter(__seq3, nameof(global::AntDesign.Input<TValue>.ValueExpression), __arg3);
        __builder.CloseComponent();
        }
        public static void CreateInput_2<TValue>(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder, int seq, int __seq0, global::System.String __arg0, int __seq1, TValue __arg1, int __seq2, global::Microsoft.AspNetCore.Components.EventCallback<TValue> __arg2, int __seq3, global::System.Linq.Expressions.Expression<global::System.Func<TValue>> __arg3)
        {
        __builder.OpenComponent<global::AntDesign.Input<TValue>>(seq);
        __builder.AddComponentParameter(__seq0, nameof(global::AntDesign.Input<TValue>.
#nullable restore
#line (164,61)-(164,72) "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor"
Placeholder

#line default
#line hidden
#nullable disable
        ), __arg0);
        __builder.AddComponentParameter(__seq1, nameof(global::AntDesign.Input<TValue>.
#nullable restore
#line (164,26)-(164,31) "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor"
Value

#line default
#line hidden
#nullable disable
        ), __arg1);
        __builder.AddComponentParameter(__seq2, nameof(global::AntDesign.Input<TValue>.ValueChanged), __arg2);
        __builder.AddComponentParameter(__seq3, nameof(global::AntDesign.Input<TValue>.ValueExpression), __arg3);
        __builder.CloseComponent();
        }
        public static void CreateInput_3<TValue>(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder, int seq, int __seq0, global::System.String __arg0, int __seq1, TValue __arg1, int __seq2, global::Microsoft.AspNetCore.Components.EventCallback<TValue> __arg2, int __seq3, global::System.Linq.Expressions.Expression<global::System.Func<TValue>> __arg3)
        {
        __builder.OpenComponent<global::AntDesign.Input<TValue>>(seq);
        __builder.AddComponentParameter(__seq0, nameof(global::AntDesign.Input<TValue>.
#nullable restore
#line (167,61)-(167,72) "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor"
Placeholder

#line default
#line hidden
#nullable disable
        ), __arg0);
        __builder.AddComponentParameter(__seq1, nameof(global::AntDesign.Input<TValue>.
#nullable restore
#line (167,26)-(167,31) "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor"
Value

#line default
#line hidden
#nullable disable
        ), __arg1);
        __builder.AddComponentParameter(__seq2, nameof(global::AntDesign.Input<TValue>.ValueChanged), __arg2);
        __builder.AddComponentParameter(__seq3, nameof(global::AntDesign.Input<TValue>.ValueExpression), __arg3);
        __builder.CloseComponent();
        }
        public static void CreateInput_4<TValue>(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder, int seq, int __seq0, global::System.String __arg0, int __seq1, TValue __arg1, int __seq2, global::Microsoft.AspNetCore.Components.EventCallback<TValue> __arg2, int __seq3, global::System.Linq.Expressions.Expression<global::System.Func<TValue>> __arg3)
        {
        __builder.OpenComponent<global::AntDesign.Input<TValue>>(seq);
        __builder.AddComponentParameter(__seq0, nameof(global::AntDesign.Input<TValue>.
#nullable restore
#line (170,59)-(170,70) "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor"
Placeholder

#line default
#line hidden
#nullable disable
        ), __arg0);
        __builder.AddComponentParameter(__seq1, nameof(global::AntDesign.Input<TValue>.
#nullable restore
#line (170,26)-(170,31) "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor"
Value

#line default
#line hidden
#nullable disable
        ), __arg1);
        __builder.AddComponentParameter(__seq2, nameof(global::AntDesign.Input<TValue>.ValueChanged), __arg2);
        __builder.AddComponentParameter(__seq3, nameof(global::AntDesign.Input<TValue>.ValueExpression), __arg3);
        __builder.CloseComponent();
        }
        public static void CreateInput_5<TValue>(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder, int seq, int __seq0, global::System.String __arg0, int __seq1, TValue __arg1, int __seq2, global::Microsoft.AspNetCore.Components.EventCallback<TValue> __arg2, int __seq3, global::System.Linq.Expressions.Expression<global::System.Func<TValue>> __arg3)
        {
        __builder.OpenComponent<global::AntDesign.Input<TValue>>(seq);
        __builder.AddComponentParameter(__seq0, nameof(global::AntDesign.Input<TValue>.
#nullable restore
#line (173,63)-(173,74) "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor"
Placeholder

#line default
#line hidden
#nullable disable
        ), __arg0);
        __builder.AddComponentParameter(__seq1, nameof(global::AntDesign.Input<TValue>.
#nullable restore
#line (173,26)-(173,31) "C:\Users\Delet\Desktop\zcode\ShareArkUI\ShareArkUI.razor"
Value

#line default
#line hidden
#nullable disable
        ), __arg1);
        __builder.AddComponentParameter(__seq2, nameof(global::AntDesign.Input<TValue>.ValueChanged), __arg2);
        __builder.AddComponentParameter(__seq3, nameof(global::AntDesign.Input<TValue>.ValueExpression), __arg3);
        __builder.CloseComponent();
        }
    }
}
#pragma warning restore 1591
